Add case when support
kotlin-orm/ktorm pull request #413
Opened 2022-07-14 11:26 UTC by zuisong

2022-07-15 10:09 UTC, vincentlauvlwj commented
- Ktorm 的 SQL 语法支持都会配合相应的 DSL 写法，没有让用户手动创建 expression 的道理
- SQL case when 不仅支持 `case when condition1 then statement1 when condition2 then statement2 end` 的写法，还支持在 case 关键字后跟一个变量，比如 `case var when value1 then statement1 when value2 then statement2 end`

综上，这个功能实现不完整，暂不考虑合并

2022-07-15 11:26 UTC, zuisong commented
针对第二点, 我在最新的代码里已经提供支持了

第一点是是准备周末的时候再写工具方法让用户方便的创建的, 现在也已经更新上来了 , 可以帮忙再次看一下吗?  

文档还没更新。觉得可以合并的时候, 我一起把文档也更新上, 还有一些方法名和参数名使用了kotlin的关键字, 也有待商量怎么处理, 可以讨论出一个合理的方案, 我一起改进

2022-07-15 11:27 UTC, zuisong commented
可能需要重新打开这个MR才能看到最新的代码 😄

2022-07-15 12:34 UTC, vincentlauvlwj commented
不好意思，你继续写吧

2022-07-15 12:55 UTC, vincentlauvlwj commented
推荐一种 DSL 的写法：

```kotlin
val query = database
    .from(Employees)
    .select((CASE(Employees.name) WHEN "vince" THEN 1 WHEN "mary" THEN 2 ELSE 3).aliased("c"))
    .where { xxx }
```

不带参数：

```kotlin
val query = database
    .from(Employees)
    .select((CASE() WHEN (Employees.name eq "vince") THEN 1 WHEN (Employees.name eq "mary") THEN 2 ELSE 3).aliased("c"))
    .where { xxx }
```

`CASE`, `WHEN`, `THEN`, `ELSE` 这些函数统一用大写命名，避免与 Kotlin 的关键字冲突

2022-07-15 13:26 UTC, zuisong commented
想了一下，这种中缀表达式的dsl对换行不太友好，可能要提供多种dsl的写法，这种写法很直观，可以作为其中一种写法

> 推荐一种 DSL 的写法：
> 
> 
> 
> ```kotlin
> 
> val query = database
> 
>     .from(Employees)
> 
>     .select((CASE(Employees.name) WHEN "vince" THEN 1 WHEN "mary" THEN 2 ELSE 3).aliased("c"))
> 
>     .where { xxx }
> 
> ```
> 
> 
> 
> 不带参数：
> 
> 
> 
> ```kotlin
> 
> val query = database
> 
>     .from(Employees)
> 
>     .select((CASE() WHEN (Employees.name eq "vince") THEN 1 WHEN (Employees.name eq "mary") THEN 2 ELSE 3).aliased("c"))
> 
>     .where { xxx }
> 
> ```
> 
> 
> 
> `CASE`, `WHEN`, `THEN`, `ELSE` 这些函数统一用大写命名，避免与 Kotlin 的关键字冲突

2022-07-15 14:13 UTC, vincentlauvlwj commented
中缀函数并没有禁止用户使用传统方式调用，不存在对换行不友好的问题，写成链式就好了：

```kotlin
val expr = CASE(Employees.name)
    .WHEN("vince").THEN(1)
    .WHEN("mary").THEN(2)
    .ELSE(3)
```

不带参数：

```kotlin
val expr = CASE()
    .WHEN(Employees.name eq "vince").THEN(1)
    .WHEN(Employees.name eq "mary").THEN(2)
    .ELSE(3)
```

2022-07-15 14:42 UTC, zuisong commented
> 中缀函数并没有禁止用户使用传统方式调用，不存在对换行不友好的问题，写成链式就好了：
> 
> ```kotlin
> val expr = CASE(Employees.name)
>     .WHEN("vince").THEN(1)
>     .WHEN("mary").THEN(2)
>     .ELSE(3)
> ```
> 
> 不带参数：
> 
> ```kotlin
> val expr = CASE()
>     .WHEN(Employees.name eq "vince").THEN(1)
>     .WHEN(Employees.name eq "mary").THEN(2)
>     .ELSE(3)
> ```

已经实现了第一版， 还是有一点瑕疵， 可以看一下代码里的评论

2022-07-16 03:07 UTC, vincentlauvlwj requested changes
大概浏览了你的代码，有两个比较大的问题需要修改：

- DSL 的写法保留一种就好了，太多的写法会引发混乱，建议把你之前的遗留代码删了
- `SqlExpressionVisitor.visitCaseWhen` 不要留空
- 所有 public 的类和函数都应该添加文档注释，你可以在你本地运行 `./gradlew clean build` 试试，不符合规范的无法成功构建

2022-07-16 07:52 UTC, zuisong commented
> 大概浏览了你的代码，有三个比较大的问题需要修改：
> 
> * DSL 的写法保留一种就好了，太多的写法会引发混乱，建议把你之前的遗留代码删了
> * `SqlExpressionVisitor.visitCaseWhen` 不要留空
> * 所有 public 的类和函数都应该添加文档注释，你可以在你本地运行 `./gradlew clean build` 试试，不符合规范的无法成功构建

好的, dsl 我更新了一下。现在第一个then 依然要传 expression , 不能传变量进来, 暂时没有想到好办法解决这个问题

这对上面这些问题, 我今天晚些时候会修复

2022-07-17 03:41 UTC, zuisong commented
问题都改好了， 麻烦再看一下呢， 有什么问题我继续改进一下 😄

2022-07-18 09:59 UTC, vincentlauvlwj requested changes
修改意见参见代码评论，另外请修改 [ktorm.maven-publish.gradle.kts](https://github.com/kotlin-orm/ktorm/blob/master/buildSrc/src/main/kotlin/ktorm.maven-publish.gradle.kts) 加入你的 ID

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/dsl/CaseWhenExpression.kt
> +)
不需要定义这两个类，直接使用 `CaseWhenExpression` 即可

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/dsl/CaseWhenExpression.kt
> +/*
这个文件改名为 `CaseWhen.kt` 更好，它里面的内容跟 `SqlExpression` 无关，不要混淆了

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/dsl/CaseWhenExpression.kt
> +    return this.caseWhenExpression!!.copy(
`this.caseWhenExpression` 不会导致空指针吗

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/expression/SqlExpressionVisitor.kt
> +    protected open fun <T : Any, V : Any> visitCaseWhen(expr: CaseWhenExpression<T, V>): CaseWhenExpression<T, V> {
`visitCaseWhen` 的实现请参考其他 `visit` 函数

1. 保持代码风格的一致
2. 调用 `copy` 函数之前需要判断各个字段是否有变化

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/expression/SqlExpressions.kt
> +public data class CaseWhenExpression<V : Any, T : Any> internal constructor(
泛型参数只需要一个 T，表示整个表达式的返回类型，V 可以去掉，用到 V 的地方可以改成 `ScalarExpression<*>`

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/expression/SqlExpressions.kt
> +    internal val whenSqlType: SqlType<V>,
`whenSqlType` 可以去掉

2022-07-18 09:59 UTC, vincentlauvlwj commented on ktorm-core/src/main/kotlin/org/ktorm/expression/SqlFormatter.kt
> +        expr.whenThenConditions.forEach { (condition, result) ->
请跟 ktorm 保持一致的代码风格，仅仅只是遍历的话，我们一般不用 `forEach`，而是用 `for in` 循环

2022-09-21 12:57 UTC, merged

2022-09-21 13:00 UTC, vincentlauvlwj commented
已合并，3.6.0 发布